version: 0.1
 
phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm -v
      - node -v
      - cd app1 && npm install
      - cd app2 && npm install
      - cd app3 && npm install
  post_build:
    commands:
      - echo Build completed on `date`
